{% set name = "agriculture-vlab" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/agriculture-vlab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9bc89a4b8737bac2e2378ada01f180d3e77deac9fd25ad10167506b0066c68a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - avl = avl.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - boto3 >=1.20.24
    - cartopy >=0.21.1
    - click >=8.0
    - matplotlib-base >=3.0
    - numpy >=1.17
    - pandas >=1.3
    - pyproj
    - python >={{ python_min }}
    - tenacity >=8.2.2
    - xarray >=0.18.2
    - xcube >=0.10.1
    - zarr >=2.8

test:
  requires:
    - python {{ python_min }}
  imports:
    - avl

about:
  home: https://github.com/agriculture-vlab/agriculture-vlab
  summary: An environment for analysis of agricultural earth observation data
  description: |
    The Agriculture Virtual Laboratory (AVL) is an online environment for the
    analysis of agricultural earth observation data. This package provides
    Python and command-line interfaces for various AVL user and administrator
    funtions.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://docs.agriculturevlab.eu/
  dev_url: https://github.com/agriculture-vlab/agriculture-vlab

extra:
  recipe-maintainers:
    - pont-us
    - forman
