{% set name = "agriculture-vlab" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/agriculture-vlab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 11c07bd31291ba3475de5984fa7a584051a30b5021ccf4916871017c7d47703e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - avl = avl.cli:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - boto3 >=1.20.24
    - click >=8.0
    - numpy >=1.17
    - pandas >=1.3
    - pyproj
    - xarray >=0.18.2
    - xcube >=0.10.1
    - zarr >=2.8

test:
  imports:
    - avl

about:
  home: https://github.com/agriculture-vlab/agriculture-vlab
  summary: An environment for analysis of agricultural earth observation data
  description: |
    The Agriculture Virtual Laboratory (AVL) is an online environment for the
    analysis of agricultural earth observation data. This package provides
    Python and command-line interfaces for various AVL user and administrator
    funtions.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://docs.agriculturevlab.eu/
  dev_url: https://github.com/agriculture-vlab/agriculture-vlab

extra:
  recipe-maintainers:
    - pont-us
    - forman
